version: '3.8'

services: 

  postgres:
    image: postgres
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_PASSWORD: super@hard10@Password
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: ./src/FindAFriend.Api/Dockerfile